name: Electron Desktop App Build

on:
  push:
    branches: [ "main" ]

jobs:
    Macos-Build:
        runs-on: macos-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
    
            - name: Build Electron Desktop App
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                npm install -y
                npm install -g electron-builder -y
                electron-builder --mac --linux tar.xz --win 
                ls ./dist

            - name: upload app
              if: always()
              continue-on-error: true
              uses: actions/upload-artifact@master
              with:
                  name: Macos Desktop Application
                  path: |
                    ./dist/electron-demo-1.0.0.dmg
                    ./dist/electron-demo-1.0.0-mac.zip
                    ./dist/electron-demo_1.0.0_amd64.snap
                    ./dist/electron-demo-1.0.0.tar.xz
                    ./dist/electron-demo Setup 1.0.0.exe

    # Ubuntu-Build:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Check out Git repository
    #           uses: actions/checkout@v2

    #         - name: Setup Node.js
    #           uses: actions/setup-node@v3
    #           with:
    #             node-version: 18
    
    #         - name: Build Electron Desktop App
    #           env:
    #             GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #           run: |
    #             npm install -y
    #             npm install -g electron-builder -y
    #             electron-builder --mac
    #             electron-builder --linux tar.xz

    #         - name: upload app
    #           if: always()
    #           continue-on-error: true
    #           uses: actions/upload-artifact@master
    #           with:
    #               name: Ubuntu Desktop Application
    #               path: |
    #                 ./dist/electron-demo_1.0.0_amd64.snap
    #                 ./dist/electron-demo-1.0.0.tar.xz
        
    # Windows-Build:
    #     runs-on: windows-latest

    #     steps:
    #         - name: Check out Git repository
    #           uses: actions/checkout@v2

    #         - name: Setup Node.js
    #           uses: actions/setup-node@v3
    #           with:
    #             node-version: 18
    
    #         - name: Build Electron Desktop App
    #           env:
    #             GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #           run: |
    #             npm install -y
    #             npm install -g electron-builder -y
    #             electron-builder --win

    #         - name: upload app
    #           if: always()
    #           continue-on-error: true
    #           uses: actions/upload-artifact@master
    #           with:
    #             name: Windows Desktop Application
    #             path: |
    #               ./dist/electron-demo Setup 1.0.0.exe